### ISSUE TITLE
Does not compile on Arduino IDE 1.8.20

### ISSUE THREAD

**Issue by stefan63** [madhephaestus/ESP32Encoder#61]
Does not compile on Arduino IDE 1.8.20 in Windows 11
However did compile without issues on IDE 1.8.13 on my Macbook Air

Errors on 1.8.20

`C:\Users\Stefan\Documents\Arduino\libraries\TouchDRO_Interface-master\ESP32_Quad_Encoder.cpp: In function 'void pcnt_isr(void*)':
C:\Users\Stefan\Documents\Arduino\libraries\TouchDRO_Interface-master\ESP32_Quad_Encoder.cpp:42:20: error: 'PCNT' was not declared in this scope
  int intr_status = PCNT.int_st.val;
                    ^
At global scope:
cc1plus.exe: warning: unrecognized command line option '-Wno-frame-address'
exit status 1
Error compiling for board DOIT ESP32 DEVKIT V1.`
